#!/usr/bin/env python3
"""AUTO-GENERATED by scripts/generate_flow.py — DO NOT EDIT MANUALLY

Generate REPO_ANALYSIS/full_text_flow.md by parsing the actual source code.

Reads:
  - revo_norm/text_normalizer.py    (normalize_text, _normalize_with_entity_extraction)
  - revo_norm/entity_extractor.py   (EntityType enum, entity patterns)
  - revo_norm/normalizer_en.py      (text_normalize steps)
  - revo_norm/normalizer_ms.py      (normalize_malay steps)
  - revo_norm/shared_features.py     (feature functions)

Usage:
    uv run python scripts/generate_flow.py
"""

from __future__ import annotations

import ast
import textwrap
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

ROOT = Path(__file__).resolve().parent.parent
REPO_ANALYSIS = ROOT / "REPO_ANALYSIS"
OUTPUT_FILE = REPO_ANALYSIS / "full_text_flow.md"

HEADER = (
    "<!-- AUTO-GENERATED by scripts/generate_flow.py — DO NOT EDIT MANUALLY -->\n"
)


# ---------------------------------------------------------------------------
# Helpers — AST parsing
# ---------------------------------------------------------------------------


def _read_module(name: str) -> str:
    """Read a module file under revo_norm/."""
    path = ROOT / "revo_norm" / name
    return path.read_text(encoding="utf-8")


def _parse(source: str) -> ast.Module:
    return ast.parse(source)


def _get_function_source(source: str, func_name: str) -> str:
    """Return the full source text of a top-level function by name."""
    tree = _parse(source)
    for node in ast.walk(tree):
        if (
            isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
            and node.name == func_name
            and hasattr(node, "lineno")
            and hasattr(node, "end_lineno")
        ):
            lines = source.splitlines()
            return "\n".join(lines[node.lineno - 1 : node.end_lineno])
    return ""


def _get_function_body(source: str, func_name: str) -> list[ast.stmt]:
    """Return the body statements of a top-level function."""
    tree = _parse(source)
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == func_name:
            return node.body
    return []


def _flatten_stmts(stmts: list[ast.stmt]) -> list[ast.stmt]:
    """Flatten try/if blocks to get all leaf-level statements."""
    result: list[ast.stmt] = []
    for stmt in stmts:
        if isinstance(stmt, ast.Try):
            result.extend(_flatten_stmts(stmt.body))
            for handler in stmt.handlers:
                result.extend(_flatten_stmts(handler.body))
            result.extend(_flatten_stmts(stmt.finalbody))
            result.extend(_flatten_stmts(stmt.orelse))
        elif isinstance(stmt, ast.If):
            result.append(stmt)
            result.extend(_flatten_stmts(stmt.body))
            result.extend(_flatten_stmts(stmt.orelse))
        else:
            result.append(stmt)
    return result


def _stmt_to_source(stmt: ast.stmt, full_source: str) -> str:
    """Best-effort: extract the source lines for a single AST statement."""
    if hasattr(stmt, "lineno") and hasattr(stmt, "end_lineno"):
        lines = full_source.splitlines()
        start = stmt.lineno - 1
        end = stmt.end_lineno  # end_lineno is 1-based inclusive
        return "\n".join(lines[start:end])
    return ast.dump(stmt)


def _extract_calls(stmts: list[ast.stmt], full_source: str) -> list[dict]:
    """Extract ordered call-like steps from a list of AST statements.

    Returns a list of dicts with keys:
        kind   - "assign" | "expr" | "if" | "for" | "return"
        source - the source text (trimmed)
        calls  - list of called function names found in this statement
    """
    steps: list[dict] = []
    for stmt in stmts:
        src = _stmt_to_source(stmt, full_source).strip()
        if not src:
            continue

        # Collect call names inside this statement
        calls: list[str] = []
        for node in ast.walk(stmt):
            if isinstance(node, ast.Call):
                name = _call_name(node)
                if name:
                    calls.append(name)

        kind = type(stmt).__name__.lower()
        # Simplify kind names
        kind_map = {
            "assign": "assign",
            "expr": "expr",
            "if": "if",
            "for": "for",
            "return": "return",
            "try": "try",
        }
        kind = kind_map.get(kind, kind)

        steps.append({"kind": kind, "source": src, "calls": calls})
    return steps


def _call_name(node: ast.Call) -> str:
    """Get a readable name from a Call node."""
    func = node.func
    if isinstance(func, ast.Name):
        return func.id
    if isinstance(func, ast.Attribute):
        return func.attr
    return ""


# ---------------------------------------------------------------------------
# Extractors for specific code structures
# ---------------------------------------------------------------------------


def extract_entity_types(source: str) -> list[tuple[str, str]]:
    """Extract EntityType enum members as (name, value) pairs."""
    tree = _parse(source)
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == "EntityType":
            members = []
            for item in node.body:
                if isinstance(item, ast.Assign) and len(item.targets) == 1:
                    name = item.targets[0].id if isinstance(item.targets[0], ast.Name) else ""
                    val = ""
                    if isinstance(item.value, ast.Constant):
                        val = str(item.value.value)
                    members.append((name, val))
            return members
    return []


def extract_entity_pattern_methods(source: str) -> list[str]:
    """Extract _compile_* method names from EntityExtractor."""
    tree = _parse(source)
    methods = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == "EntityExtractor":
            for item in node.body:
                if isinstance(item, ast.FunctionDef) and item.name.startswith("_compile_"):
                    methods.append(item.name)
    return methods


def extract_normalizer_steps(source: str, func_name: str) -> list[str]:
    """Extract ordered regex.sub and function call steps from a normalizer function.

    Returns list of human-readable step descriptions.
    """
    body = _get_function_body(source, func_name)
    steps = []

    for stmt in body:
        src = _stmt_to_source(stmt, source).strip()
        # Skip comments-only, docstrings, empty
        if not src or src.startswith("#") or src.startswith('"""') or src.startswith("'''"):
            continue

        # Look for re.sub(pattern, handler, text) calls
        for node in ast.walk(stmt):
            if isinstance(node, ast.Call):
                # re.sub calls: the handler function name tells us the step
                if isinstance(node.func, ast.Attribute) and node.func.attr == "sub":
                    if node.args and isinstance(node.args[1], ast.Name):
                        handler = node.args[1].id
                        # Pattern variable name
                        pattern_name = ""
                        if node.args and isinstance(node.args[0], ast.Name):
                            pattern_name = node.args[0].id
                        steps.append(_describe_regex_step(handler, pattern_name))
                    elif node.args and isinstance(node.args[1], ast.Lambda):
                        # Lambda handler - use pattern name
                        if node.args and isinstance(node.args[0], ast.Name):
                            steps.append(f"Regex sub with pattern {node.args[0].id}")
                # Direct function calls like expand_contractions(text)
                elif isinstance(node.func, ast.Name) and node.func.id in (
                    "expand_contractions",
                    "expand_abbreviations",
                ):
                    steps.append(_describe_function_step(node.func.id))

    return steps


def _describe_regex_step(handler: str, pattern: str) -> str:
    """Generate a human-readable description for a regex substitution step."""
    descriptions = {
        # English normalizer
        "normalize_date": "Dates → spoken form (DD/MM/YYYY)",
        "normalize_currency": "Currency → spoken form ($100 → 'one hundred dollar')",
        "normalize_time_no_meridian": "Times without AM/PM → spoken form",
        "normalize_time": "Times with AM/PM → spoken form",
        "normalize_percentage": "Percentages → spoken form (25% → 'twenty five percent')",
        "normalize_decimal": "Decimals → spoken form (3.5 → 'three point five')",
        "normalize_dashed_digits": "Dashed digits → spoken digits (1-2-3 → 'one dash two dash three')",
        "normalize_ordinal": "Ordinals → spoken form (1st → 'first')",
        "normalize_number": "Numbers → words (42 → 'forty two')",
        "normalize_number_with_commas": "Comma numbers → words (1,000,000 → 'one million')",
        "normalize_mixed_alnum": "Mixed alphanumeric → spoken",
        "expand_currency_k_suffix": "Currency K-suffix expansion (RM30K → RM30000)",
        # Malay normalizer
        "normalize_date_ymd": "YYYY-MM-DD dates → spoken Malay dates",
        "normalize_percentage_ms": "Percentages → 'peratus'",
        "normalize_decimal_ms": "Decimals → 'perpuluhan' form",
        "normalize_dashed_digits_ms": "Dashed digits → Malay digits",
    }
    return descriptions.get(handler, f"{handler}() — regex sub")


def _describe_function_step(func_name: str) -> str:
    descriptions = {
        "expand_contractions": "Contractions → expanded (don't → 'do not', I'm → 'I am')",
        "expand_abbreviations": "Abbreviations → expanded (Dr. → 'doctor')",
    }
    return descriptions.get(func_name, f"{func_name}()")


# ---------------------------------------------------------------------------
# Pipeline step extraction from text_normalizer.py
# ---------------------------------------------------------------------------


def extract_pipeline_steps(source: str) -> list[dict]:
    """Extract the ordered steps from normalize_text() (single unified pipeline).

    Returns list of dicts: {step_num, label, description, module, details}
    """
    body = _get_function_body(source, "normalize_text")
    flat = _flatten_stmts(body)
    steps = []

    for stmt in flat:
        src = _stmt_to_source(stmt, source).strip()
        if not src:
            continue

        # Detect significant steps by looking for key function calls
        step = _identify_step(src)
        if step:
            steps.append(step)

    return steps


def _identify_step(source_line: str) -> dict | None:
    """Identify a pipeline step from a source line."""
    # Currency K-suffix expansion
    if "CURRENCY_T_SUFFIX_PATTERN" in source_line and "expand_currency_t_suffix" in source_line:
        return {
            "phase": 1,
            "label": "Currency K/M/B/T suffix expansion",
            "description": "Order: T → B → M → K (largest to smallest)",
            "module": "currency_utils.py",
        }
    if "CURRENCY_B_SUFFIX_PATTERN" in source_line:
        return None  # Part of currency suffix block
    if "CURRENCY_M_SUFFIX_PATTERN" in source_line:
        return None  # Part of currency suffix block
    if "CURRENCY_K_SUFFIX_PATTERN" in source_line and "expand_currency_k_suffix" in source_line:
        return None  # Part of currency suffix block

    # Entity extraction
    if "EntityExtractor()" in source_line:
        return {
            "phase": 2,
            "label": "Entity extraction → placeholders",
            "description": "Extract emails, URLs, currency, dates, times, etc. → <<<TYPE_N>>>",
            "module": "entity_extractor.py",
        }

    # Pronunciation mappings
    if "apply_pronunciation_mappings" in source_line:
        return {
            "phase": 3,
            "label": "Pronunciation mappings (HIGHEST PRIORITY)",
            "description": "JSON → 'jay son', GUI → 'gooey', ML → preserved",
            "module": "pronunciation_mappings.py",
        }

    # Placeholder stashing
    if "_stash_placeholders" in source_line:
        return {
            "phase": 4,
            "label": "Stash placeholders (protect from downstream)",
            "description": "<<<TYPE_N>>> → safe alphabetic tokens",
            "module": "text_normalizer.py",
        }

    # Pronunciation overrides
    if "apply_pronunciation_overrides" in source_line and "cfg" in source_line:
        return {
            "phase": 5,
            "label": "Pronunciation overrides",
            "description": "twenty-three → 'twenty tree', a/l → 'anak lelaki'",
            "module": "text_normalizer.py → apply_pronunciation_overrides",
        }

    # Elongated words
    if "normalize_elongated_text" in source_line and "cfg" in source_line:
        return {
            "phase": 5,
            "label": "Elongated word normalization",
            "description": "betuiii → 'betui', celakaaa → 'celaka'",
            "module": "shared_features.py",
        }

    # Measurements
    if "normalize_measurements" in source_line and "cfg" in source_line:
        return {
            "phase": 5,
            "label": "Measurement normalization",
            "description": "5km → 'five kilometers', 2kg → 'two kilograms'",
            "module": "shared_features.py",
        }

    # X-kali
    if "normalize_x_kali_text" in source_line and "cfg" in source_line:
        return {
            "phase": 5,
            "label": "X-kali (multiplier) normalization",
            "description": "10x → 'ten times', 3x → 'tiga kali'",
            "module": "shared_features.py",
        }

    # Language-specific normalization
    if "text_normalizer_en" in source_line:
        return {
            "phase": 6,
            "label": "Language-specific normalization (English)",
            "description": "normalizer_en.py → text_normalize()",
            "module": "normalizer_en.py",
        }
    if "text_normalizer_ms" in source_line:
        return {
            "phase": 6,
            "label": "Language-specific normalization (Malay)",
            "description": "normalizer_ms.py → normalize_malay()",
            "module": "normalizer_ms.py",
        }

    # Spacing normalization
    if "_normalize_whitespace" in source_line and "cfg" in source_line:
        return {
            "phase": 7,
            "label": "Whitespace normalization",
            "description": "Collapse multiple spaces → single space, strip edges",
            "module": "text_normalizer.py",
        }

    # Sound words
    if "smart_remove_sound_words" in source_line and "cfg" in source_line:
        return {
            "phase": 7,
            "label": "Sound word removal (if configured)",
            "description": "Remove background sounds from TTS input",
            "module": "tts_utils.py → smart_remove_sound_words",
        }

    # Abbreviation expansion
    if "expand_abbreviations(protected_text" in source_line:
        return {
            "phase": 7,
            "label": "Abbreviation expansion (currently no-op)",
            "description": "expand_abbreviations() — placeholder",
            "module": "text_normalizer.py",
        }

    # Letter-period & acronym expansion
    if "replace_letter_period_sequences" in source_line and "cfg" in source_line:
        return {
            "phase": 7,
            "label": "Letter-period & Acronym expansion",
            "description": "I.B.M. → 'I B M', NASA → preserved, API → 'A P I'",
            "module": "text_normalizer.py → replace_letter_period_sequences",
        }

    # Comma insertion
    if "insert_comma_after_repeated_words" in source_line and "min_repeat" not in source_line:
        return {
            "phase": 7,
            "label": "Comma insertion for repeated words",
            "description": "'test test test test' → 'test test test, test'",
            "module": "text_normalizer.py",
        }

    # Special character replacement
    if "special_replace" in source_line and "cfg" in source_line:
        return {
            "phase": 7,
            "label": "Special character replacement",
            "description": "& → 'and', % → 'percent', $ → 'dollar', @ → 'at', etc.",
            "module": "text_normalizer.py → special_replace",
        }

    # Restore placeholders/entities
    if "_unstash_placeholders" in source_line:
        return {
            "phase": 8,
            "label": "Restore placeholders → spoken entities",
            "description": "Convert stashed tokens back to entity placeholders, then to spoken form",
            "module": "text_normalizer.py → _restore_entities",
        }

    return None


# ---------------------------------------------------------------------------
# Markdown generation
# ---------------------------------------------------------------------------


def generate_markdown(
    entity_types: list[tuple[str, str]],
    entity_pattern_methods: list[str],
    pipeline_steps: list[dict],
    en_steps: list[str],
    ms_steps: list[str],
) -> str:
    """Generate the full flow markdown document."""
    sections = []

    # --- Entry Point ---
    sections.append(textwrap.dedent("""\
        # Revo Norm — Full Text Flow Diagram

        ## Entry Point

        ```
        normalize_text(text, language="en", profile=None, disable=None)
               |
               v
         +------------------------------------------------------------------+
         |  1. Build Config from profile + disable list                     |
         |  2. Strip whitespace, return "" if empty                         |
         +------------------------------------------------------------------+
                    |
                    v
            +-------------------+
            |   SINGLE PIPELINE |
            |  (unified flow)   |
            +-------------------+
        ```
    """))

    # --- Unified Pipeline ---
    pipeline_block = _build_pipeline_block(entity_types, pipeline_steps)
    sections.append(pipeline_block)

    # --- Language-specific normalizers ---
    lang_block = _build_language_normalizer_block(en_steps, ms_steps)
    sections.append(lang_block)

    # --- Example flows ---
    examples_block = _build_example_flows(entity_types)
    sections.append(examples_block)

    return "\n".join(sections)


def _build_pipeline_block(
    entity_types: list[tuple[str, str]],
    steps: list[dict],
) -> str:
    """Build the unified pipeline section."""
    lines = [
        "---",
        "",
        "## PIPELINE (single unified flow)",
        "",
        "```",
        "INPUT TEXT",
        "    |",
        "    v",
    ]

    # Group steps by phase, deduplicating by label within each phase
    phase_labels = {
        1: "PRE-PROCESSING",
        2: "ENTITY EXTRACTION",
        3: "PRONUNCIATION",
        4: "PLACEHOLDER PROTECTION",
        5: "FEATURE-GATED PROCESSING",
        6: "LANGUAGE NORMALIZER",
        7: "POST-PROCESSING",
        8: "ENTITY RESTORE",
    }

    for phase_num in sorted({s["phase"] for s in steps}):
        phase_steps = [s for s in steps if s["phase"] == phase_num]
        phase_label = phase_labels.get(phase_num, f"PHASE {phase_num}")

        # Deduplicate by label within each phase
        seen: set[str] = set()
        unique_steps: list[dict] = []
        for s in phase_steps:
            if s["label"] not in seen:
                seen.add(s["label"])
                unique_steps.append(s)
        phase_steps = unique_steps

        lines.append(f" {'=' * 66}")
        lines.append(f" |  {phase_label}")
        lines.append(f" {'=' * 66}")

        for step in phase_steps:
            desc = step.get("description", "")
            module = step.get("module", "")
            lines.append("            |")
            lines.append(f" +{'-' * 66}+")
            lines.append(f" | {step['label']:<65}|")
            if desc:
                lines.append(f" |   {desc:<64}|")
            if module:
                mod_text = f"({module})"
                lines.append(f" | {mod_text:<65}|")
            lines.append(f" +{'-' * 66}+")

        # After entity extraction phase, list entity types
        if phase_num == 2:
            lines.append("")
            lines.append("  Entity types extracted (gated by Config):")
            for name, val in entity_types:
                lines.append(f"    {name:<16} -> <<<{val.upper()}_N>>>")

    lines.append("            |")
    lines.append("            v")
    lines.append("        OUTPUT TEXT")
    lines.append("```")
    return "\n".join(lines)


def _build_language_normalizer_block(en_steps: list[str], ms_steps: list[str]) -> str:
    """Build the language-specific normalizer section."""
    lines = [
        "---",
        "",
        "## LANGUAGE-SPECIFIC NORMALIZERS",
        "",
        "### English (`normalizer_en.py` -> `text_normalize()`)",
        "",
        "```",
        "INPUT",
        "  |",
    ]
    for step in en_steps:
        lines.append(f"  |- {step}")
    lines.append("OUTPUT")
    lines.append("```")

    lines.extend([
        "",
        "### Malay (`normalizer_ms.py` -> `normalize_malay()`)",
        "",
        "```",
        "INPUT",
        "  |",
    ])
    for step in ms_steps:
        lines.append(f"  |- {step}")
    lines.append("OUTPUT")
    lines.append("```")

    return "\n".join(lines)


def _build_example_flows(entity_types: list[tuple[str, str]]) -> str:
    """Build template-based example flows using actual entity types."""
    # Build entity type string for examples
    et_names = [name for name, _ in entity_types]

    lines = [
        "---",
        "",
        "## EXAMPLE FLOWS",
        "",
        '### Example 1: "The API costs RM50K on 15/08/2025" (en)',
        "",
        "```",
        '"The API costs RM50K on 15/08/2025"',
        "    |",
        "    |- Currency K-suffix: RM50K -> RM50000",
        "    |",
        "    |- Entity extraction:",
        "    |   CURRENCY='RM50000', DATE='15/08/2025'",
        "    |   'The API costs <<<CURRENCY_1>>> on <<<DATE_2>>>'",
        "    |",
        "    |- Pronunciation: API -> 'A P I'",
        "    |",
        "    |- English normalizer processes non-entity text",
        "    |",
        "    |- Restore entities as spoken form",
        "    |",
        "    v",
        "Final output (varies by exact regex matches)",
        "```",
        "",
    ]

    # Generate examples using actual entity types
    if "TEMPERATURE" in et_names and "CURRENCY" in et_names:
        lines.extend([
            '### Example 2: "Suhu 25C, RM450 untuk ML project" (ms)',
            "",
            "```",
            '"Suhu 25C, RM450 untuk ML project"',
            "    |",
            "    |- Entity extraction:",
            "    |   'Suhu <<<TEMPERATURE_1>>>, <<<CURRENCY_2>>> untuk ML project'",
            "    |   entities: [TEMPERATURE='25C', CURRENCY='RM450']",
            "    |",
            "    |- Pronunciation: ML -> 'M L'",
            "    |",
            "    |- Feature-gated: measurements, x-kali",
            "    |",
            "    |- Malay normalizer processes non-entity text",
            "    |",
            "    |- Restore entities as spoken form",
            "    |   <<<TEMPERATURE_1>>> -> 'dua puluh lima darjah selsius'",
            "    |   <<<CURRENCY_2>>>    -> 'empat ratus lima puluh ringgit'",
            "    |",
            "    v",
            '"dua puluh lima darjah selsius, empat ratus lima puluh ringgit untuk M L project"',
            "```",
            "",
        ])

    if "TIME" in et_names:
        lines.extend([
            '### Example 3: "Parse JSON file at 3:30 pm" (en)',
            "",
            "```",
            '"Parse JSON file at 3:30 pm"',
            "    |",
            "    |- Entity extraction:",
            "    |   'Parse JSON file at <<<TIME_1>>>'",
            "    |   entities: [TIME='3:30 pm']",
            "    |",
            "    |- Pronunciation: JSON -> 'J son'",
            "    |   'Parse J son file at <<<TIME_1>>>'",
            "    |",
            "    |- English normalizer processes non-entity text",
            "    |",
            "    |- Restore TIME",
            "    |   <<<TIME_1>>> -> 'three thirty p m'",
            "    |",
            "    v",
            '"Parse J son file at three thirty p m"',
            "```",
            "",
        ])

    if "FRACTION" in et_names and "HARI_BULAN" in et_names:
        lines.extend([
            '### Example 4: "Harga 3/4 kg tepung 10hb" (ms)',
            "",
            "```",
            '"Harga 3/4 kg tepung 10hb"',
            "    |",
            "    |- Entity extraction:",
            "    |   FRACTION='3/4', HARI_BULAN='10hb'",
            "    |   'Harga <<<FRACTION_1>>> kg tepung <<<HARI_BULAN_2>>>'",
            "    |",
            "    |- Feature-gated: measurements ('kg' -> 'kilogram')",
            "    |",
            "    |- Malay normalizer processes non-entity text",
            "    |",
            "    |- Restore entities as spoken form",
            "    |   <<<FRACTION_1>>>    -> 'tiga per empat'",
            "    |   <<<HARI_BULAN_2>>> -> 'sepuluh hari bulan'",
            "    |",
            "    v",
            '"Harga tiga per empat kilogram tepung sepuluh hari bulan"',
            "```",
        ])

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    """Parse source files and generate the flow diagram."""
    print("Reading source files...")

    text_normalizer_src = _read_module("text_normalizer.py")
    entity_extractor_src = _read_module("entity_extractor.py")
    normalizer_en_src = _read_module("normalizer_en.py")
    normalizer_ms_src = _read_module("normalizer_ms.py")

    print("Extracting entity types...")
    entity_types = extract_entity_types(entity_extractor_src)
    entity_pattern_methods = extract_entity_pattern_methods(entity_extractor_src)

    print("Extracting pipeline steps...")
    pipeline_steps = extract_pipeline_steps(text_normalizer_src)

    print("Extracting English normalizer steps...")
    en_steps = extract_normalizer_steps(normalizer_en_src, "text_normalize")

    print("Extracting Malay normalizer steps...")
    ms_steps = extract_normalizer_steps(normalizer_ms_src, "normalize_malay")

    print("Generating markdown...")
    content = generate_markdown(
        entity_types=entity_types,
        entity_pattern_methods=entity_pattern_methods,
        pipeline_steps=pipeline_steps,
        en_steps=en_steps,
        ms_steps=ms_steps,
    )

    output = HEADER + "\n" + content

    # Ensure output directory exists
    REPO_ANALYSIS.mkdir(parents=True, exist_ok=True)

    OUTPUT_FILE.write_text(output, encoding="utf-8")
    print(f"Generated {OUTPUT_FILE}")
    print(f"  Entity types found: {len(entity_types)}")
    print(f"  Pipeline steps: {len(pipeline_steps)}")
    print(f"  English normalizer steps: {len(en_steps)}")
    print(f"  Malay normalizer steps: {len(ms_steps)}")


if __name__ == "__main__":
    main()
